### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ChanJeff123** [pat-odoo/TwoRC522_RPi2-3#1]
pi@raspberrypi:~/pymaker $ cd 2-TwoRC522_RPi2-3/
pi@raspberrypi:~/pymaker/2-TwoRC522_RPi2-3 $ sudo python run_main_test.py
Traceback (most recent call last):
  File "run_main_test.py", line 15, in <module>
    from module.card_reader import CardReader
ImportError: No module named module.card_reader

where is module.card_reader? need to DL something?

**Comment by TakoSquid** [comment]
You need to create an empty file named "__init__.py" in the module directory

**Comment by ChanJeff123** [comment]
thanks i already fixed it

**Comment by kasssupport** [comment]
sorry but new to Linux and I'm a bit confused what does the init.py file do and how do I solve the problem listed above?

**Comment by kasssupport** [comment]
I tried adding _init-.py in the module directory but the problem is enduring.
I'm using python3.7.2 so I'm not sure if that would make a difference. 
I  have tried from .card_reader import CardReader but to no avail.
I tried from module import card_reader as CardReader but no go.
I'm open to suggestions.
many thanks

**Comment by mepsd** [comment]
Hey, new to python added int.py but still getting the same error please help me!

**Comment by mepsd** [comment]
solved inside module directory create __init__.py file that will solve this issue
